services:
  - type: web
    name: chatafinder
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      ./render_build.sh
    startCommand: gunicorn chatafinder_core.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false  # set manually in dashboard from your Render Postgres