# Generated by Django 4.2.23 on 2025-06-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('card_1', models.CharField(max_length=100)),
                ('card_2', models.CharField(max_length=100)),
                ('card_3', models.CharField(max_length=100)),
                ('horoscope_message', models.TextField()),
            ],
        ),
    ]
